rocketmq:
  producer:
    group: consumer-group
  name-server: 127.0.0.1:9876
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mq_consumer_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
