rocketmq:
  name-server: 192.168.145.131:9876
  consumer:
    group: consumer-group
    send-message-timeout: 3000
    # 消费者拉取消息的最大数量
    pull-batch-size: 32

spring:
  datasource:
    url: jdbc:mysql://192.168.145.131:3306/parking?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: user
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: cn.ltynote.rocketmq.model.po
server:
  port: 8081

